//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAIBay.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAIBay.WebSite.Resources.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string AcercaDe {
            get {
                return ResourceManager.GetString("AcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar categoría.
        /// </summary>
        public static string ActualizarCategoria {
            get {
                return ResourceManager.GetString("ActualizarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar producto.
        /// </summary>
        public static string ActualizarProducto {
            get {
                return ResourceManager.GetString("ActualizarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar proveedor.
        /// </summary>
        public static string ActualizarProveedor {
            get {
                return ResourceManager.GetString("ActualizarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al carrito.
        /// </summary>
        public static string AgregarAlCarrito {
            get {
                return ResourceManager.GetString("AgregarAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregue una nueva direccion.
        /// </summary>
        public static string AgregueUnaNuevaDireccion {
            get {
                return ResourceManager.GetString("AgregueUnaNuevaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Año {
            get {
                return ResourceManager.GetString("Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        public static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poseemos mas de 500 productos con el precio mas bajo y la mejor calidad del mercado..
        /// </summary>
        public static string BannerslideCalidadParrafo {
            get {
                return ResourceManager.GetString("BannerslideCalidadParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contamos con la mejor calidad.
        /// </summary>
        public static string BannerslideCalidadTitulo {
            get {
                return ResourceManager.GetString("BannerslideCalidadTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poseemos mas de 200 unidades de transporte para realizar envios sin a cargo a traves del todo el país.
        /// </summary>
        public static string BannerslideComprasParrafo {
            get {
                return ResourceManager.GetString("BannerslideComprasParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disfruta de tus compras sin moverte de tu casa.
        /// </summary>
        public static string BannerslideComprasTitulo {
            get {
                return ResourceManager.GetString("BannerslideComprasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestro objetivo es que hagas tus compras desde la comodidad de tu casa y recibiendo promociones diarias al unirte a nuestra comunidad..
        /// </summary>
        public static string BannerslideComunidadParrafo {
            get {
                return ResourceManager.GetString("BannerslideComunidadParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a nuestra comunidad.
        /// </summary>
        public static string BannerslideComunidadTitulo {
            get {
                return ResourceManager.GetString("BannerslideComunidadTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito.
        /// </summary>
        public static string Carrito {
            get {
                return ResourceManager.GetString("Carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogo.
        /// </summary>
        public static string Catalogo {
            get {
                return ResourceManager.GetString("Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo postal.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colaboradores.
        /// </summary>
        public static string Colaboradores {
            get {
                return ResourceManager.GetString("Colaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para UAI-BAY es fundamental cuidar su capital humano porque sus colaboradores son la cara visible de la empresa y del servicio que se entrega. Uno de los ejes centrales es que ellos se sientan bien, recompensados y motivados para lo cual nos hemos propuesto desarrollar el talento y mejorar la calidad de vida de cada uno de ellos.
        /// </summary>
        public static string ColaboradoresParrafo {
            get {
                return ResourceManager.GetString("ColaboradoresParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        public static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunidad.
        /// </summary>
        public static string Comunidad {
            get {
                return ResourceManager.GetString("Comunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apoyamos el emprendimiento ya que creemos que es la mejor vía para superar la pobreza, ademas porque este valor esta incorporado en el ADN de la empresa, ya que nuestro presidente es un emprendedor innato. Esto quiere decir que nuestro compromiso esta en apoyar al emprendimiento nacional, local y a los pequeños productores, para generar un impacto social positivo. Por esto, en Agosto de 2007, concretamos una alianza con Fondo Esperanza, fundación sin fines de lucro que entrega créditos y educación emprended [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ComunidadParrafo {
            get {
                return ResourceManager.GetString("ComunidadParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su compra.
        /// </summary>
        public static string ConfirmeSuCompra {
            get {
                return ResourceManager.GetString("ConfirmeSuCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactenos.
        /// </summary>
        public static string Contactenos {
            get {
                return ResourceManager.GetString("Contactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright © 2016 UAIBay Todos los derechos reservados..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de envio.
        /// </summary>
        public static string CostoDeEnvio {
            get {
                return ResourceManager.GetString("CostoDeEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva categoria.
        /// </summary>
        public static string CrearNuevaCategoria {
            get {
                return ResourceManager.GetString("CrearNuevaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo producto.
        /// </summary>
        public static string CrearNuevoProducto {
            get {
                return ResourceManager.GetString("CrearNuevoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo proveedor.
        /// </summary>
        public static string CrearNuevoProveedor {
            get {
                return ResourceManager.GetString("CrearNuevoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿COMO RECUPERO MI CONTRASEÑA?.
        /// </summary>
        public static string CuartaPreguntaFrecuente {
            get {
                return ResourceManager.GetString("CuartaPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una vez registrado en el sistema, en caso de no recordar su contraseña, se puede solicitar una nueva contraseña. Para esto se debe ingresar a la pestaña de Login y elegir la opción &quot;Olvidaste tu contraseña?&quot;. Se debe ingresar el email de su cuenta y hacer click en &quot;Recuperar contraseña&quot;.En unos instantes llegara un email a su casilla de correo con su nueva contraseña..
        /// </summary>
        public static string CuartaRespuesta {
            get {
                return ResourceManager.GetString("CuartaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuota s/i de.
        /// </summary>
        public static string CuotaSinInteresDe {
            get {
                return ResourceManager.GetString("CuotaSinInteresDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuotas s/i de.
        /// </summary>
        public static string CuotasSinInteresDe {
            get {
                return ResourceManager.GetString("CuotasSinInteresDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripción {
            get {
                return ResourceManager.GetString("Descripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el producto?.
        /// </summary>
        public static string DeseaEliminarElProducto {
            get {
                return ResourceManager.GetString("DeseaEliminarElProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el proveedor?.
        /// </summary>
        public static string DeseaEliminarElProveedor {
            get {
                return ResourceManager.GetString("DeseaEliminarElProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la categoría?.
        /// </summary>
        public static string DeseaEliminarLaCategoria {
            get {
                return ResourceManager.GetString("DeseaEliminarLaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de categoría.
        /// </summary>
        public static string DetallesDeCategoria {
            get {
                return ResourceManager.GetString("DetallesDeCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del producto.
        /// </summary>
        public static string DetallesDelProducto {
            get {
                return ResourceManager.GetString("DetallesDelProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del proveedor.
        /// </summary>
        public static string DetallesDelProveedor {
            get {
                return ResourceManager.GetString("DetallesDelProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Dirección {
            get {
                return ResourceManager.GetString("Dirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñado por los 4 Fantasticos.
        /// </summary>
        public static string Diseñado {
            get {
                return ResourceManager.GetString("Diseñado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        public static string Domicilio {
            get {
                return ResourceManager.GetString("Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uh... parece que ha ocurrido un error inesperado.
        /// </summary>
        public static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAQ&apos;S.
        /// </summary>
        public static string FAQS {
            get {
                return ResourceManager.GetString("FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string Femenino {
            get {
                return ResourceManager.GetString("Femenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar pago.
        /// </summary>
        public static string FinalizarPago {
            get {
                return ResourceManager.GetString("FinalizarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frances.
        /// </summary>
        public static string Frances {
            get {
                return ResourceManager.GetString("Frances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Gracias por comprar en UAIBay!.
        /// </summary>
        public static string GraciasPorComprarEnUAIBay {
            get {
                return ResourceManager.GetString("GraciasPorComprarEnUAIBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gratis.
        /// </summary>
        public static string Gratis {
            get {
                return ResourceManager.GetString("Gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion de contacto.
        /// </summary>
        public static string InformacionContacto {
            get {
                return ResourceManager.GetString("InformacionContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su codigo de descuento.
        /// </summary>
        public static string IngreseSuCodigoDeDescuento {
            get {
                return ResourceManager.GetString("IngreseSuCodigoDeDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesion.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión.
        /// </summary>
        public static string IniciaSesion {
            get {
                return ResourceManager.GetString("IniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al Inicio.
        /// </summary>
        public static string IrAlInicio {
            get {
                return ResourceManager.GetString("IrAlInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenganse en contacto!.
        /// </summary>
        public static string Mantenganseencontacto {
            get {
                return ResourceManager.GetString("Mantenganseencontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string Masculino {
            get {
                return ResourceManager.GetString("Masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medioambiente.
        /// </summary>
        public static string Medioambiente {
            get {
                return ResourceManager.GetString("Medioambiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operar de manera respetuosa con el medioambiente y generar conciencia, ya que el medioambiente es un tema que no puede esperar..
        /// </summary>
        public static string MedioambienteParrafo {
            get {
                return ResourceManager.GetString("MedioambienteParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mision.
        /// </summary>
        public static string Mision {
            get {
                return ResourceManager.GetString("Mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Satisfacer las necesidades del cliente interno y externo: desarrollando, fabricando y comercializando productos y servicios de excelente calidad. Con un personal capacitado para dar soluciones integrales que generen bienestar, compromiso y trabajo en equipo..
        /// </summary>
        public static string MisionParrafo {
            get {
                return ResourceManager.GetString("MisionParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto total a pagar.
        /// </summary>
        public static string MontoTotalAPagar {
            get {
                return ResourceManager.GetString("MontoTotalAPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo del titular de la tarjeta.
        /// </summary>
        public static string NombreCompletoTitularTarjeta {
            get {
                return ResourceManager.GetString("NombreCompletoTitularTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudimos encontrar esa pagina.
        /// </summary>
        public static string NoPudimosEncontrarEsaPagina {
            get {
                return ResourceManager.GetString("NoPudimosEncontrarEsaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra informacion.
        /// </summary>
        public static string Nuestrainformacion {
            get {
                return ResourceManager.GetString("Nuestrainformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtene nuestras mas recientes novedades de nuestro sitio....
        /// </summary>
        public static string NuestrasNovedadesParrafo {
            get {
                return ResourceManager.GetString("NuestrasNovedadesParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras novedades.
        /// </summary>
        public static string NuestrasNovedadesTitulo {
            get {
                return ResourceManager.GetString("NuestrasNovedadesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras redes sociales.
        /// </summary>
        public static string NuestrasRedesSociales {
            get {
                return ResourceManager.GetString("NuestrasRedesSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestros ultimos productos.
        /// </summary>
        public static string NuestrosUltimosProductos {
            get {
                return ResourceManager.GetString("NuestrosUltimosProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva categoria.
        /// </summary>
        public static string NuevaCategoria {
            get {
                return ResourceManager.GetString("NuevaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo producto.
        /// </summary>
        public static string NuevoProducto {
            get {
                return ResourceManager.GetString("NuevoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo proveedor.
        /// </summary>
        public static string NuevoProveedor {
            get {
                return ResourceManager.GetString("NuevoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de tarjeta.
        /// </summary>
        public static string NumeroDeTarjeta {
            get {
                return ResourceManager.GetString("NumeroDeTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        public static string Pagar {
            get {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partido.
        /// </summary>
        public static string Partido {
            get {
                return ResourceManager.GetString("Partido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de compra.
        /// </summary>
        public static string PrecioCompra {
            get {
                return ResourceManager.GetString("PrecioCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de venta.
        /// </summary>
        public static string PrecioVenta {
            get {
                return ResourceManager.GetString("PrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntas frecuentes.
        /// </summary>
        public static string PreguntasFrecuentes {
            get {
                return ResourceManager.GetString("PreguntasFrecuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿HAY QUE PAGAR PARA UNIRSE A LA COMUNIDAD UAY-BAY?.
        /// </summary>
        public static string PrimeraPreguntaFrecuente {
            get {
                return ResourceManager.GetString("PrimeraPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No,en absoluto.Para unirse a nuestra comunidad basta con algunos datos personales..
        /// </summary>
        public static string PrimeraRespuesta {
            get {
                return ResourceManager.GetString("PrimeraRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿COMO CAMBIAR MI CONTRASEÑA?.
        /// </summary>
        public static string QuintaPreguntaFrecuente {
            get {
                return ResourceManager.GetString("QuintaPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una vez registrado y logeado en el sistema, ingresar a la pestaña de &quot;Cuenta&quot; y clickear en la opcion &quot;Cambiar contraseña&quot;. Por ultimo,escriba su nueva contraseña y confirmela..
        /// </summary>
        public static string QuintaRespuesta {
            get {
                return ResourceManager.GetString("QuintaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que unicamente realizamos envios dentro de Zona Oeste..
        /// </summary>
        public static string RecuerdeEnviosZonaOeste {
            get {
                return ResourceManager.GetString("RecuerdeEnviosZonaOeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse!.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrese.
        /// </summary>
        public static string Registrese {
            get {
                return ResourceManager.GetString("Registrese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita la contraseña.
        /// </summary>
        public static string RepetirContraseña {
            get {
                return ResourceManager.GetString("RepetirContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿CUAL ES EL COSTO DE ENVIO?.
        /// </summary>
        public static string SegundaPreguntaFrecuente {
            get {
                return ResourceManager.GetString("SegundaPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno, el envio es gratuito..
        /// </summary>
        public static string SegundaRespuesta {
            get {
                return ResourceManager.GetString("SegundaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el número de cuotas en las que desea realizar el pago.
        /// </summary>
        public static string SeleccioneNumeroCuotas {
            get {
                return ResourceManager.GetString("SeleccioneNumeroCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione su dirección.
        /// </summary>
        public static string SeleccioneSuDireccion {
            get {
                return ResourceManager.GetString("SeleccioneSuDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿COMO APLICAR UN CODIGO DE DESCUENTO?.
        /// </summary>
        public static string SeptimaPreguntaFrecuente {
            get {
                return ResourceManager.GetString("SeptimaPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los codigos de descuento se deben aplicar al final de la compra insertando el codigo que le sera enviado por mail. Recuerde que estos codigos poseen una fecha de vencimiento.
        /// </summary>
        public static string SeptimaRespuesta {
            get {
                return ResourceManager.GetString("SeptimaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿COMO COMPRAR?.
        /// </summary>
        public static string SextaPreguntaFrecuente {
            get {
                return ResourceManager.GetString("SextaPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar es muy sencillo, una vez logeado en la pagina, usted podra ver un Catalago con los productos que contamos y seleccionar todos aquellos productos que quiera comprar. Al final de la seleccion podra ver un listado con los productos seleecionados y el total a abonar.
        /// </summary>
        public static string SextaRespuesta {
            get {
                return ResourceManager.GetString("SextaRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubTotal.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Teléfono {
            get {
                return ResourceManager.GetString("Teléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿QUE FORMAS DE PAGO DISPONE UAI-BAY?.
        /// </summary>
        public static string TerceraPreguntaFrecuente {
            get {
                return ResourceManager.GetString("TerceraPreguntaFrecuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted podra abonar por tarjeta de credito a traves de nuestra pagina web o directamente abonar en efectivo cuando reciba sus productos en su domicilio..
        /// </summary>
        public static string TerceraRespuesta {
            get {
                return ResourceManager.GetString("TerceraRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        public static string Tienda {
            get {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser el supermercado más importante en todo el litoral central, logrando la distinción tanto de clientes como de proveedores y competidores. Mantener y aumentar, las ventas y el número de clientes, año a año..
        /// </summary>
        public static string VisionParrafo {
            get {
                return ResourceManager.GetString("VisionParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al catalogo.
        /// </summary>
        public static string VolverAlCatalogo {
            get {
                return ResourceManager.GetString("VolverAlCatalogo", resourceCulture);
            }
        }
    }
}
