//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAIBay.ORM.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public Carrito()
        {
            this.ItemCarrito = new HashSet<ItemCarrito>();
        }
    
        public int IdCarrito { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual ICollection<ItemCarrito> ItemCarrito { get; set; }
    }
}
