//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAIBay.ORM.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ActivityLog = new HashSet<ActivityLog>();
            this.DataLog = new HashSet<DataLog>();
            this.Direccion = new HashSet<Direccion>();
            this.ErrorLog = new HashSet<ErrorLog>();
            this.History = new HashSet<History>();
            this.TarjetaCredito = new HashSet<TarjetaCredito>();
            this.Venta = new HashSet<Venta>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int UserId { get; set; }
        public int DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Telefono { get; set; }
        public bool Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public int AccessFailedCount { get; set; }
        public System.DateTime DeleteOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLog { get; set; }
        public virtual ICollection<DataLog> DataLog { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<TarjetaCredito> TarjetaCredito { get; set; }
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
